# schema.yml
version: 2

sources:
  - name: raw
    database: le-wagon-2204      # your GCP project ID
    schema: dbt_course             # or use {{ target.schema }} for environment-safe naming
    loader: bigquery                 # identifies how data is loaded (fivetran, airbyte, etc.)
    freshness:
      warn_after: {count: 12, period: hour}   # warn if data older than 12 hours
      error_after: {count: 24, period: hour}  # error if data older than 24 hours
    tables:
      - name: sales
        identifier: raw_gz_sales     
        description: sales of Greenweez / we have one row per product_id found in each orders_id        #4.1 Adding Source Documentation
         # Freshness testing
        loaded_at_field: "TIMESTAMP(date_date)"
        config: 
          freshness:
          warn_after: {count: 50000, period: day}
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
          - name: quantity
            description: the quantity of products purchased for a given order
        tests:
           - unique:
               column_name: "(orders_id || '-' || pdt_id)"
           ## OR ## if dbt_utils is installed
           - dbt_utils.unique_combination_of_columns:
               combination_of_columns:
                 - orders_id
                 - pdt_id
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:                                            #4.1 Adding Source Documentation
        - name: products_id
          description: Primary key
          tests:                                             #4.2 - Test
          - unique
          - not_null
        - name: purchase_price
          description: the purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: shipping data for Greenweez orders
        columns:                                             #4.1 Adding Source Documentation
           - name: orders_id
             description: Primary key
             tests:                                             #4.2 Tests
             - unique
             - not_null
           - name: shipping_fee
             description: the price the customer pays for shipping
           - name: log_cost
             description: the cost of preparing the parcel in the distribution centre/warehouse
           - name: ship_cost
             description: shipping cost paid by Greenweez to the carrier/logistics provider
      - name: adwords
        identifier: raw_gz_adwords
        description: raw Adwords campaign performance data
        columns:
          - name: date_date
            description: date of activity
          - name: campaign_key
            description: campaign identifier
          - name: campaign_name
            description: name of the campaign
          - name: ad_cost
            description: advertising spend
          - name: paid_source
            description: source platform
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
        tests:
          - unique:
              column_name: "(CAST(date_date AS STRING) || '-' || campaign_key || '-' || campgn_name)"

## chall 3 3.2
      - name: bing
        identifier: raw_gz_bing
        description: raw Bing Ads campaign performance data
        columns:
          - name: date_date
            description: date of activity
          - name: campaign_key
            description: campaign identifier
          - name: campaign_name
            description: name of the campaign
          - name: ad_cost
            description: advertising spend
          - name: paid_source
            description: source platform
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
        tests:
          - unique:
              column_name: "(CAST(date_date AS STRING) || '-' || campaign_key || '-' || campgn_name)"


      - name: criteo
        identifier: raw_gz_criteo
        description: raw Criteo campaign performance data
        columns:
          - name: date_date
            description: date of activity
          - name: campaign_key
            description: campaign identifier
          - name: campaign_name
            description: name of the campaign
          - name: ad_cost
            description: advertising spend
          - name: paid_source
            description: source platform
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
        tests:
          - unique:
              column_name: "(CAST(date_date AS STRING) || '-' || campaign_key || '-' || campgn_name)"


      - name: facebook
        identifier: raw_gz_facebook
        description: raw Facebook Ads campaign performance data
        columns:
          - name: date_date
            description: date of activity
          - name: campaign_key
            description: campaign identifier
          - name: campaign_name
            description: name of the campaign
          - name: ad_cost
            description: advertising spend
          - name: paid_source
            description: source platform
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks
        tests:
          - unique:
              column_name: "(CAST(date_date AS STRING) || '-' || campaign_key || '-' || campgn_name)"
          
# Intermediate #
models: ## Documentation and TEST 5. bien mettre "models" pour garder le bon chemin et pas chercher dans Big query
      - name: int_orders_margin
        description: margin calculation per order
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: margin
            description: margin = revenue - purchase_cost
            tests:
              - not_null
          - name: Purchase_cost
            description: purchase_cost = quantity * purchase_price
            tests:
              - not_null
          - name: date_date
            description: date of the order
            tests:
              - not_null
          - name: revenue
            description: sum of revenue per order
            tests:
              - not_null
          - name: quantity
            description: sum of quantity per order
            tests:
              - not_null

      - name: int_sales_margin
        description: margin calculation per order line / product sales
        columns:
          - name: orders_id
            description: orders key
            tests:
              - not_null
          - name: products_id
            description: products key
            tests:
              - not_null
          - name: margin
            description: margin = revenue - purchase_cost
            tests:
              - not_null
          - name: Purchase_cost
            description: purchase_cost = quantity * purchase_price
            tests:
              - not_null
          - name: date_date
            description: date of the order
            tests:
              - not_null
          - name: revenue
            description: sum of revenue per order
            tests:
              - not_null
          - name: quantity
            description: sum of quantity per order
            tests:
              - not_null
        tests:
          - unique:
              column_name: "(orders_id || '-' || products_id)"

      - name: int_orders_operational
        description: operational margin calculation per order
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: date_date
            description: date of the order
            tests:
              - not_null
          - name: operational_margin
            description: operational_margin = margin + shipping_fee - log_cost - ship_cost
          - name: quantity
            description: sum of quantity per order
            tests:
              - not_null
          - name: revenue
            description: sum of revenue per order
            tests:
              - not_null
          - name: purchase_cost
            description: purchase_cost = quantity * purchase_price
            tests:
              - not_null
          - name: margin
            description: margin = revenue - purchase_cost
            tests:
              - not_null
          - name: shipping_fee
            description: the price the customer pays for shipping
          - name: log_cost
            description: the cost of preparing the parcel in the distribution centre/warehouse
          - name: ship_cost
            description: shipping cost paid by Greenweez to the carrier/logistics provide
      ##chall 3 3.2
      - name: int_campaigns
        description: "Union of all marketing campaign staging models (Adwords, Bing, Criteo, Facebook)."
        columns:
          - name: date_date
            description: "Date of the campaign event."
            tests:
              - not_null
          - name: paid_source
            description: "Marketing channel (adwords, bing, criteo, facebook)."
            tests:
              - not_null

          - name: campaign_key
            description: "Unique campaign identifier."
            tests:
              - not_null

          - name: campaign_name
            description: "Readable name of the campaign."
            tests:
              - not_null

          - name: ad_cost
            description: "Cost associated with the campaign."
            tests:
              - not_null

          - name: impression
            description: "Number of impressions received."

          - name: click
            description: "Number of clicks received."
        tests:
        - unique:
            column_name: "(CAST(date_date AS STRING) || '-' || campaign_key || '-' || campaign_name)"

      - name: int_campaigns_day
        description: "Daily aggregated marketing campaign metrics across all channels."
        columns:
          - name: date_date
            description: "Date of the aggregated campaign metrics."
            tests:
              - not_null
              - unique

          - name: ads_cost
            description: "Total advertising cost for the day."
            tests:
              - not_null

          - name: ads_impression
            description: "Total impressions for the day."
            tests:
              - not_null

          - name: ads_clicks
            description: "Total clicks for the day."
            tests:
              - not_null